FROM node:14.17.2-slim

RUN npm install -g serve

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

#COPY --chown=node package*.json ./

#RUN yarn install

COPY --chown=node ./ .

#RUN yarn build

EXPOSE 5000

CMD ["serve", "-s", "build"]
