version: "3"

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: chat-backend
        ports:
            - 3011:3011
        volumes:
            - .:/home/node/app
        deploy:
            resources:
                limits:
                  memory: 1G

    db:
        build: .docker/postgres
        container_name: db-chat
        ports:
            - 5432:5432
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=chat